
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int annd = 28;
  public static final int coma = 20;
  public static final int igual = 16;
  public static final int ptcoma = 2;
  public static final int intt = 35;
  public static final int parder = 4;
  public static final int mayorque = 22;
  public static final int llavec = 15;
  public static final int llavea = 14;
  public static final int dividido = 8;
  public static final int elsee = 21;
  public static final int mayorigualque = 27;
  public static final int menos = 6;
  public static final int iff = 13;
  public static final int EOF = 0;
  public static final int mas = 5;
  public static final int error = 1;
  public static final int entero = 10;
  public static final int por = 7;
  public static final int str = 34;
  public static final int dospuntos = 19;
  public static final int menorque = 23;
  public static final int id = 9;
  public static final int oor = 29;
  public static final int noigual = 25;
  public static final int elevado = 31;
  public static final int menorigualque = 26;
  public static final int corchetec = 18;
  public static final int corchetea = 17;
  public static final int igualar = 24;
  public static final int noot = 30;
  public static final int print = 33;
  public static final int parizq = 3;
  public static final int modulo = 32;
  public static final int decimal = 11;
  public static final int cadena = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ptcoma",
  "parizq",
  "parder",
  "mas",
  "menos",
  "por",
  "dividido",
  "id",
  "entero",
  "decimal",
  "cadena",
  "iff",
  "llavea",
  "llavec",
  "igual",
  "corchetea",
  "corchetec",
  "dospuntos",
  "coma",
  "elsee",
  "mayorque",
  "menorque",
  "igualar",
  "noigual",
  "menorigualque",
  "mayorigualque",
  "annd",
  "oor",
  "noot",
  "elevado",
  "modulo",
  "print",
  "str",
  "intt"
  };
}

